/**
 * Vite build plugin: prepare prod-mode runtime SDK switching.
 *
 * Big picture (see doc/tech-design/icebergfeng/api-example-vue3-prod-sdk-switching.md):
 *
 *   In prod the SDK (`tuikit-atomicx-vue3`) is NOT in the demo bundle.
 *   The bundle ships its own copies of `vue` / `vue-router` /
 *   `@tencentcloud/uikit-base-component-vue3` plus the demo's business
 *   code. At runtime the demo:
 *
 *     1. Exposes its loaded vue / vue-router / uikit-base instances
 *        on `window.__ATOMICX_HOST__` (done by `main.ts`).
 *     2. Reads the user-selected SDK version from `localStorage` and
 *        does a dynamic `import("https://esm.sh/tuikit-atomicx-vue3@<ver>?external=...")`.
 *     3. The SDK bundle returned by esm.sh has THREE bare specifiers
 *        — `vue`, `vue-router`, `@tencentcloud/uikit-base-component-vue3`
 *        — kept bare because of the `?external=` query. Everything
 *        else (lite-chat, chat-uikit-engine-lite, tui-core-lite,
 *        tuiroom-engine-js, all their sub-paths) is already rewritten
 *        by esm.sh to absolute esm.sh URLs, so the browser doesn't
 *        need an importmap entry for any of them.
 *     4. The three remaining bare specifiers are routed by a static
 *        importmap in `index.html` to three host-shim files that we
 *        emit during `closeBundle`. Each shim re-exports its
 *        corresponding `__ATOMICX_HOST__` instance under every named
 *        export the upstream package publishes.
 *
 *   Switching SDK versions is therefore a pure browser-side operation:
 *     localStorage.atomicx.selectedVersion = "x.y.z"  → reload  → the
 *     next dynamic import picks up the new URL and esm.sh serves the
 *     new version. The demo bundle does not change.
 *
 * Plugin scope:
 *   `apply: 'build'` — completely inert in dev. Dev mode uses the
 *   workspace / vendor flow via `sdkSwitcherPlugin.mjs`.
 *
 * Plugin hooks used:
 *   - `transformIndexHtml`: inject the static importmap right after
 *     <head>. The map has only 3 fixed entries — there is no version
 *     number to bake in here, no per-build state.
 *   - `closeBundle`: write the three host-shim files (
 *     `dist/host-shim/vue.js`, etc.) by re-extracting the public
 *     export surface of vue / vue-router / uikit-base from disk.
 */
import { resolve } from 'node:path';
import { generateHostShims } from './genHostShim.mjs';

/**
 * The single source of truth for "packages that must be shared
 * between the demo bundle and the SDK loaded from esm.sh".
 *
 * Each entry drives THREE downstream artefacts and they MUST stay in
 * lockstep:
 *
 *   1. `name` — the bare specifier the SDK imports. Sent to esm.sh
 *      as `?external=<csv of names>` so esm.sh leaves the specifier
 *      bare in its transpiled output.
 *   2. `shimFile` — the importmap target file the browser fetches
 *      when resolving the bare specifier. Generated by
 *      `scripts/genHostShim.mjs` during `closeBundle`.
 *   3. `hostKey` — the key on `window.__ATOMICX_HOST__` under which
 *      `main.ts` publishes the demo bundle's already-loaded
 *      instance. The shim file reads `window.__ATOMICX_HOST__[hostKey]`
 *      and re-exports every named export from it.
 *
 * Adding/removing an entry here is the ONLY edit needed to roll out
 * a new shared singleton: this module exposes derived constants
 * (CSV string for esm.sh, list of {pkg, hostKey, file} for the shim
 * generator) so neither `main.ts` nor `genHostShim.mjs` needs to
 * duplicate the list.
 *
 * Adding a name to esm.sh `?external=` without also adding a
 * host-shim + importmap entry → silent dual-instance bug (the SDK
 * sees one vue, the demo sees another). The opposite mistake is
 * harmless (an unused host-shim entry).
 */
const SHARED_SINGLETONS = Object.freeze([
  Object.freeze({ name: 'vue',                                     hostKey: 'vue',        shimFile: 'vue.js' }),
  Object.freeze({ name: 'vue-router',                              hostKey: 'vueRouter',  shimFile: 'vue-router.js' }),
  Object.freeze({ name: '@tencentcloud/uikit-base-component-vue3', hostKey: 'uikitBase',  shimFile: 'uikit-base.js' }),
]);

/**
 * Comma-separated specifier list for esm.sh's `?external=` query.
 * Consumed by `main.ts` (which composes the esm.sh URL) and by the
 * downstream `sdk-source/facade.ts` types-only comment.
 */
const SHARED_SINGLETONS_CSV = SHARED_SINGLETONS.map(s => s.name).join(',');

/**
 * Compact descriptor for `scripts/genHostShim.mjs`. The shim
 * generator uses `pkg` to look up `node_modules/<pkg>`, `hostKey`
 * to compose `window.__ATOMICX_HOST__[hostKey]` reads, and `file`
 * as the output filename under `<outDir>/host-shim/`.
 */
const HOST_SHIM_TARGETS = SHARED_SINGLETONS.map(s => ({
  pkg: s.name,
  hostKey: s.hostKey,
  file: s.shimFile,
}));

/**
 * Render the bootstrap markup that installs the importmap at page load.
 *
 * ## Why runtime-computed instead of static JSON
 *
 * The static form (`<script type="importmap">{"imports":{"vue":"./host-shim/vue.js"}}`)
 * looks simpler but breaks in a specific real-world case:
 *
 *   - Deployment location is **not knowable at build time**: the same
 *     dist/ tarball can land at `https://x.com/`, at
 *     `https://x.com/hybrid/live/api-example/vue3/dev/`, or anywhere
 *     else. The CDN owner picks the path.
 *   - Static ABSOLUTE paths (`/host-shim/vue.js`) resolve against the
 *     origin and break when deployed under any subpath (404 —
 *     surfaces as `Failed to fetch dynamically imported module` from
 *     the top-level dynamic import in main.ts, with no hint pointing
 *     at the real 404-ing host-shim URL).
 *   - Static RELATIVE paths (`./host-shim/vue.js`) resolve against
 *     `document.baseURI` and work for **hash-router deployments only**
 *     (`createWebHashHistory` keeps `baseURI` stable across route
 *     changes). But `baseURI` follows the pathname under
 *     `createWebHistory`, and if the initial route happens to be a
 *     deep path, the importmap resolves against the wrong directory
 *     — same 404, same cryptic top-level error.
 *   - Static paths also fail under `<base href>` overrides, and
 *     under `file://` (some CDNs preview via file protocol during
 *     staging).
 *
 * ## What we do instead
 *
 * Emit a tiny inline `<script>` (NOT `type="module"` — must run
 * synchronously before any module script) that:
 *
 *   1. Locates its own directory URL by resolving the current inline
 *      script's `baseURI` (a browser-standard property that reflects
 *      the URL of the document that hosts the script). Since this
 *      inline script is emitted directly into index.html, its
 *      `baseURI` equals the URL of the deployed index.html file, no
 *      matter how deep the subpath.
 *   2. Strips any trailing filename (`/index.html`, `/foo.html`,
 *      etc.) to derive the **deploy-root directory URL** — an
 *      absolute URL that never depends on the current route.
 *   3. Composes the three host-shim absolute URLs from that root and
 *      writes them into a fresh `<script type="importmap">` element
 *      that we prepend into `<head>`.
 *
 * Because the importmap is BUILT AT PAGE-LOAD TIME, the paths inside
 * it are always absolute URLs pointing at the actual on-disk location
 * of the host-shim files. This is invariant against every deployment
 * concern above (deep subpath, history mode, base href, file://).
 *
 * ## Ordering & spec compliance
 *
 * The browser spec requires the importmap to be declared BEFORE the
 * first `<script type="module">` load starts. Vite emits its own
 * module script for the app bundle into <head> (see
 * `<script type="module" crossorigin src="./assets/index-xxx.js">`).
 * The bootstrap inline script is `transformIndexHtml`-inserted at
 * `<head>` open, i.e. before every other head child, so the
 * dynamically-generated `<script type="importmap">` lands in the DOM
 * before any module fetch can start. This mirrors what the spec-
 * canonical static form guarantees.
 *
 * ## Why we don't rely on `document.baseURI` at import time
 *
 * `document.baseURI` reflects `<base href>` and the current URL
 * (including pathname). If we did the resolution lazily (e.g. inside
 * a `beforeunload` handler or via `new URL('./host-shim/vue.js',
 * document.baseURI)` at any point after initial load), a
 * `createWebHistory` route change could shift the base and produce
 * a stale importmap. We snapshot the deploy root exactly once, at
 * page-load time, which is the moment `baseURI` is guaranteed to
 * equal the initially-loaded HTML's URL.
 */
function renderImportMapBootstrapScript() {
  // The list is baked into the inline script body as a plain JS
  // literal — no dynamic dispatch, no version numbers, just three
  // package-name → shim-file mappings. Kept in a `const` so future
  // additions to SHARED_SINGLETONS require zero changes here.
  const entries = SHARED_SINGLETONS.map(s => (
    `      [${JSON.stringify(s.name)}, ${JSON.stringify(s.shimFile)}]`
  )).join(',\n');

  // NOTE: We build the `</script>` close tag by string concat so this
  // template literal itself does not close the enclosing script tag
  // when the file is served as HTML at build time.
  const closeTag = '</' + 'script>';

  return `
    <script>
    /* Runtime importmap bootstrap — see injectImportMapBootstrapPlugin.mjs */
    (function () {
      try {
        // The list of shared singletons we route through host-shim.
        // Baked at build time; stays in lockstep with SHARED_SINGLETONS.
        var shims = [
${entries}
        ];

        // Locate the URL of THIS inline script. document.currentScript
        // is set to the executing <script> element for classic scripts
        // (which this is — no type="module"). Its .baseURI is the URL
        // of the containing document, i.e. the deployed index.html.
        var here = (document.currentScript && document.currentScript.baseURI) || document.baseURI;

        // Derive the directory URL by dropping everything after the
        // last '/'. Query and fragment are already excluded from
        // baseURI. Works uniformly for:
        //   https://x.com/                       -> https://x.com/
        //   https://x.com/index.html             -> https://x.com/
        //   https://x.com/a/b/                   -> https://x.com/a/b/
        //   https://x.com/a/b/index.html         -> https://x.com/a/b/
        //   https://x.com/a/b/index.html?q=1     -> https://x.com/a/b/
        //   https://x.com/a/b/index.html#/route  -> https://x.com/a/b/
        //   file:///Users/…/dist/index.html      -> file:///Users/…/dist/
        var slash = here.lastIndexOf('/');
        var rootUrl = slash >= 0 ? here.slice(0, slash + 1) : here + '/';

        // Compose absolute URLs for every host-shim. Using new URL()
        // gives us proper resolution semantics (percent-encoding,
        // dot-segment collapse, etc.).
        var imports = {};
        for (var i = 0; i < shims.length; i++) {
          var name = shims[i][0];
          var file = shims[i][1];
          imports[name] = new URL('host-shim/' + file, rootUrl).toString();
        }

        // Emit the importmap. Must land in the DOM before any
        // <script type="module"> starts loading. Because THIS
        // bootstrap runs synchronously during the initial parse of
        // <head> (we're the first child), and module scripts are
        // deferred by spec, the importmap installs in time.
        var mapEl = document.createElement('script');
        mapEl.type = 'importmap';
        mapEl.textContent = JSON.stringify({ imports: imports });
        // insertBefore(mapEl, currentScript.nextSibling) would also
        // work, but appendChild here is fine because we're still
        // inside the synchronous head-parse phase.
        (document.head || document.documentElement).appendChild(mapEl);
      } catch (err) {
        // If anything above fails we WILL fail to import the SDK
        // later. Log loudly so it shows up in devtools, but do not
        // throw — a thrown error inside a classic inline script can
        // sometimes disrupt subsequent parsing depending on browser.
        (window.console && console.error)
          && console.error('[importmap-bootstrap] failed to install importmap:', err);
      }
    })();
    ${closeTag}
  `;
}

/**
 * The vite plugin proper.
 *
 * @param {object} options
 * @param {string} options.demoRoot   Absolute path to api-example-vue3 root.
 * @param {string} [options.outDir]   Optional override for the build outDir.
 *                                    Defaults to `<demoRoot>/dist`.
 */
function injectImportMapBootstrapPlugin(options) {
  const opts = options || {};
  const demoRoot = opts.demoRoot;
  if (!demoRoot) throw new Error('injectImportMapBootstrapPlugin: demoRoot is required');
  const fallbackOutDir = resolve(demoRoot, 'dist');

  let resolvedOutDir = opts.outDir || fallbackOutDir;

  return {
    name: 'api-example-import-map-bootstrap',
    apply: 'build',

    /**
     * Pick up the actual `build.outDir` chosen by vite (the user can
     * override it on the CLI), so our host-shim files land alongside
     * the real bundle. Falls back to `<demoRoot>/dist` if vite
     * doesn't provide one (shouldn't happen, but defensive).
     */
    configResolved(config) {
      if (config && config.build && config.build.outDir) {
        // `config.build.outDir` is resolved relative to vite's `root`,
        // which may or may not equal demoRoot. Normalise via `resolve`.
        resolvedOutDir = resolve(config.root || demoRoot, config.build.outDir);
      }
    },

    /**
     * Inject the importmap bootstrap script at the very top of <head>.
     *
     * We use a literal HTML string replace (not the
     * `{tag, injectTo: 'head-prepend'}` descriptor form) because the
     * descriptor form has been observed — in this very project — to
     * weave the original <head> children INTO the middle of the
     * injected inline script body when `children` contains tag-like
     * substrings. Plain string replace makes us the sole author of
     * the bytes between `<head>` and the rest of the head — no
     * re-interleaving, no descriptor-merge quirks.
     *
     * Ordering: the bootstrap must be the FIRST child of <head> so
     * it runs before vite's own `<script type="module" src="...">`
     * for the app bundle. Module scripts are deferred by spec, so
     * even though we install the importmap synchronously during head
     * parsing, we're safely ahead of the first module fetch.
     */
    transformIndexHtml(html) {
      const injection = renderImportMapBootstrapScript();
      const headOpenRegex = /<head(\s[^>]*)?>/i;
      if (headOpenRegex.test(html)) {
        return html.replace(headOpenRegex, match => `${match}${injection}`);
      }
      // Should never happen with a vite-managed index.html, but fall
      // back to prepending so we at least make a best-effort attempt.
      return injection + html;
    },

    /**
     * After vite finishes writing the bundle, materialise the three
     * host-shim files under `<outDir>/host-shim/`. Each file re-exports
     * the corresponding package's full named-export surface from
     * `window.__ATOMICX_HOST__.<key>` — see scripts/genHostShim.mjs.
     *
     * We do this in `closeBundle` (not `generateBundle`) because we
     * want to emit physical files to disk, not virtual bundle assets
     * that go through rollup's hashing pipeline. The host-shim path
     * MUST match the importmap entries verbatim (`/host-shim/vue.js`),
     * so emitting through rollup — which would apply a hash to the
     * filename — would break the importmap.
     */
    closeBundle() {
      const shimDir = resolve(resolvedOutDir, 'host-shim');
      const summary = generateHostShims({
        demoRoot,
        outDir: shimDir,
        targets: HOST_SHIM_TARGETS,
      });
      // eslint-disable-next-line no-console
      console.log(
        `[host-shim] wrote ${summary.length} shim files to ${shimDir}:`,
      );
      for (const s of summary) {
        // eslint-disable-next-line no-console
        console.log(`[host-shim]   ${s.pkg} — ${s.count} named exports`);
      }
    },
  };
}

export {
  injectImportMapBootstrapPlugin,
  SHARED_SINGLETONS,
  SHARED_SINGLETONS_CSV,
  HOST_SHIM_TARGETS,
};
