// English (en-US) i18n resources — Audience Management state list.
//
// Key set MUST stay identical to `zh-CN/cards/liveAudience.ts`; only the
// value differs. See `menuKey()` / `cardKey()` key derivation in the
// demo. zh-CN falls back to the Chinese literals, so only the English
// side needs explicit entries here.

export const liveAudience: Record<string, string> = {
  'Card.LiveAudienceSetAdministratorFieldUserId': "User ID",
  'Menu.LiveAudience': "Audience Management",
  'Menu.LiveAudienceState': "Read audience state (audienceList / audienceCount / messageBannedUserList)",
  'Menu.LiveAudienceFetchAudienceList': "Fetch audience list",
  'Menu.LiveAudienceSetAdministrator': "Set as admin (host)",
  'Menu.LiveAudienceRevokeAdministrator': "Revoke admin (host)",
  'Menu.LiveAudienceKickUserOutOfRoom': "Kick user out (host / admin)",
  'Menu.LiveAudienceDisableSendMessage': "Mute / unmute chat (host / admin)",

  // FetchAudienceList card
  'Card.LiveAudienceFetchAudienceListDesc':
    'Manually fetch the audience list (up to 200; beyond that is degraded behavior). Returns the count and the first few users.',
  'Card.LiveAudienceFetchAudienceListFieldUserIdPlaceholder': 'Target audience userId',

  // SetAdministrator card
  'Card.LiveAudienceSetAdministratorFieldUserIdPlaceholder': 'Target audience userId',

  // RevokeAdministrator card
  'Card.LiveAudienceRevokeAdministratorFieldUserId': 'userId',

  // KickUserOutOfRoom card
  'Card.LiveAudienceKickUserOutOfRoomFieldUserId': 'userId',

  // DisableSendMessage card
  'Card.LiveAudienceDisableSendMessageFieldUserId': 'userId',
  'Card.LiveAudienceDisableSendMessageFieldIsDisable': 'isDisable (mute)',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LiveAudienceSubscribeEventDesc':
    'This group subscribes to all [[LiveAudienceEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onOwnerJoined]] events by default (demo handler; log rows prefixed with `[demo]<eventName>`). '
      + 'If a card below (unsubscribeEvent) canceled it, you can re-subscribe here by picking "all" or a single event; '
      + 'if the event is already subscribed, this call is an idempotent no-op.',
  'Card.LiveAudienceSubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-subscribe every event',
  'Card.LiveAudienceSubscribeEventToastTitle': 'Subscribed',
  'Card.LiveAudienceSubscribeEventToastDesc':
    'Next time the event fires, EventLog will also show a log row prefixed with "[demo]"',
  'Card.LiveAudienceUnsubscribeEventDesc':
    'Unsubscribe one or all events from [[LiveAudienceEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onOwnerJoined]]. After unsubscribing, when the event fires again the "[demo] xxx" '
      + 'prefixed log row no longer appears (the unprefixed regular rows are still captured by the site\'s always-on log subscription). '
      + '⚠️ In real integrations the call MUST pass the EXACT SAME handler reference used for subscribeEvent, otherwise the SDK cannot find it and silently fails.',
  'Card.LiveAudienceUnsubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-unsubscribe every event',
  'Card.LiveAudienceUnsubscribeEventToastTitle': 'Unsubscribed',
  'Card.LiveAudienceUnsubscribeEventToastDesc':
    'Next time the event fires, EventLog will no longer show the "[demo]" prefixed log row',

  // FetchAudienceList card — usage notes (G3)
  'Card.LiveAudienceFetchAudienceListNoteSummary': 'fetchAudienceList · prerequisite & semantics',
  'Card.LiveAudienceStateDesc':
    'Snapshot of reactive state: audienceList (viewer list) / audienceCount (viewer count) / messageBannedUserList (muted users), updating live with room join/leave, headcount changes, and mute events.',
  'Card.LiveAudienceStateNoteSummary': 'live-audience.state · Auto-pull on open',
  'Card.LiveAudienceStateNote0Item0':
    'Opening this card auto-calls fetchAudienceList() to load the viewer list into reactive state audienceList / audienceCount — no need to click the fetchAudienceList card. Data appears only after joining a room (currentLive.liveId present).',
  'Card.LiveAudienceFetchAudienceListNote0Item0':
    'audienceList / audienceCount are reactive refs that update live with enter/leave-room events; this API is a manual on-demand full pull (max 200). The two are complementary.',
  'Card.LiveAudienceFetchAudienceListNote0Item1':
    'Must be called AFTER entering a room (currentLive.liveId exists); calling before entering yields an empty list.',

  // SetAdministrator card — usage notes (G3)
  'Card.LiveAudienceSetAdministratorNoteSummary': 'setAdministrator · prerequisite',
  'Card.LiveAudienceSetAdministratorNote0Item0':
    'Host-only, and only while in a room (currentLive.liveId exists); calling while not in a room / not host is rejected by the underlying RoomEngine.',
  'Card.LiveAudienceSetAdministratorNote0Item1':
    'The target must still be inside the room; pass the userId of an audience member currently in this live room.',

  // RevokeAdministrator card — usage notes (G3)
  'Card.LiveAudienceRevokeAdministratorNoteSummary': 'revokeAdministrator · prerequisite',
  'Card.LiveAudienceRevokeAdministratorNote0Item0':
    'Host-only, and only while in a room (currentLive.liveId exists); calling while not in a room / not host is rejected by the underlying RoomEngine.',

  // KickUserOutOfRoom card — usage notes (G3)
  'Card.LiveAudienceKickUserOutOfRoomNoteSummary': 'kickUserOutOfRoom · prerequisite',
  'Card.LiveAudienceKickUserOutOfRoomNote0Item0':
    'Host / admin only, and only while in a room (currentLive.liveId exists); calling without room entry / permission is rejected by the underlying RoomEngine.',
  'Card.LiveAudienceKickUserOutOfRoomNote0Item1':
    'Pass the userId of an audience member currently in this live room; the kicked user receives onAudienceLeft.',

  // DisableSendMessage card — usage notes (G3)
  'Card.LiveAudienceDisableSendMessageNoteSummary': 'disableSendMessage · prerequisite',
  'Card.LiveAudienceDisableSendMessageNote0Item0':
    'Host / admin only, and only while in a room (currentLive.liveId exists); calling without room entry / permission is rejected by the underlying RoomEngine.',
  'Card.LiveAudienceDisableSendMessageNote0Item1':
    'isDisable=true mutes, false unmutes; the muted user enters messageBannedUserList, which you can observe via that ref.',
  // Group intro — verified against LiveAudienceState source
  'Card.LiveAudienceIntroSummary': 'The audience list never appears on its own; moderation calls succeed or fail at the underlying RoomEngine',
  'Card.LiveAudienceIntro0Head': 'Key points',
  'Card.LiveAudienceIntro0Item0':
    'audienceList is auto-fetched and filled only AFTER entering a room (watch currentLive.liveId); before that it is always an empty array.',
  'Card.LiveAudienceIntro0Item1':
    'audienceCount is driven by the room\'s total user count, not exactly the list length: when the total exceeds 200 it is computed as "total − 1 (host)" because the local list keeps at most 200 people, and the host is actively excluded from the list.',
  'Card.LiveAudienceIntro0Item2':
    'Moderation calls (setAdministrator / revokeAdministrator / kickUserOutOfRoom / disableSendMessage) only forward to the underlying RoomEngine — this module does no permission check, so non-host / non-admin calls are rejected by the engine directly.',
  'Card.LiveAudienceIntro1Head': 'Common pitfalls',
  'Card.LiveAudienceIntro1Item0':
    'The local audience list keeps at most 200 people; viewers not in the list are not necessarily absent — they are just not recorded locally.',
  'Card.LiveAudienceIntro1Item1':
    'fetchAudienceList clears then rebuilds the list (not incremental append), and needs the room-entered state to have data — calling before entering yields an empty list.',
  'Card.LiveAudienceIntro1Item2':
    'audienceList / audienceCount are reactive and change live with enter/leave-room and mute events — do not cache them as a one-shot snapshot.',
};
