// English (en-US) i18n resources — Barrage (Live Comments) state list.
//
// Key set MUST stay identical to `zh-CN/cards/liveBarrage.ts`; only the
// value differs. See `menuKey()` / `cardKey()` key derivation in the
// demo. zh-CN falls back to the Chinese literals, so only the English
// side needs explicit entries here.

export const liveBarrage: Record<string, string> = {
  'Card.LiveBarrageSendTextMessageFieldText': "Text",
  'Card.LiveBarrageSendTextMessageFieldExtensionInfo': "extensionInfo (JSON)",
  'Card.LiveBarrageSendCustomMessageFieldBusinessId': "Business ID",
  'Card.LiveBarrageSendCustomMessageFieldData': "data (string)",
  'Card.LiveBarrageAppendLocalTipFieldText': "Tip text",
  'Menu.LiveBarrage': "Barrage (Live Comments)",
  'Menu.LiveBarrageState': "Read barrage state (messageList)",
  'Menu.LiveBarrageSendTextMessage': "Send text barrage",
  'Menu.LiveBarrageSendCustomMessage': "Send custom business message",
  'Menu.LiveBarrageAppendLocalTip': "Append local system tip",

  // BarrageState card
  'Card.LiveBarrageStateDesc': 'Reactive state: the room-wide text-barrage queue.',
  'Card.LiveBarrageStateNoteSummary': 'messageList · what it holds',
  'Card.LiveBarrageStateNote0Item0':
    'Only holds "text barrage" (SDK-relayed + appendLocalTip local injection); custom business messages do NOT enter messageList — subscribe to onCustomMessageReceived yourself to handle them.',

  // SendTextMessage card
  'Card.LiveBarrageSendTextMessageDesc': 'Send a text barrage into the current live room.',
  'Card.LiveBarrageSendTextMessageFieldTextPlaceholder': 'Text content to send',
  'Card.LiveBarrageSendTextMessageFieldExtensionInfoHelp':
    'Optional; MUST be a JSON object with string values. The SDK does not parse it — passes it through verbatim.',
  'Card.LiveBarrageSendTextMessageToastTitle': 'Barrage sent',
  'Card.LiveBarrageSendTextMessageToastDesc':
    'The receiver gets onBarrageReceived and it is auto-added to messageList',

  // SendCustomMessage card
  'Card.LiveBarrageSendCustomMessageDesc':
    'Send a custom business message (gift / lucky-bag / entrance notice, ...).',
  'Card.LiveBarrageSendCustomMessageNoteSummary': 'sendCustomMessage · vs. text barrage',
  'Card.LiveBarrageSendCustomMessageNote0Item0':
    'Custom messages do NOT enter messageList: they are relayed only via the onCustomMessageReceived event. The receiver MUST subscribe to the event and parse `data` (usually a JSON string) itself; the SDK does no schema validation.',
  'Card.LiveBarrageSendCustomMessageFieldBusinessIdPlaceholder':
    'Business identifier, a custom string (e.g. gift / lucky_bag / entrance)',
  'Card.LiveBarrageSendCustomMessageFieldDataHelp':
    'Any string; usually the JSON-serialized business payload — the schema is agreed by the business side.',
  'Card.LiveBarrageSendCustomMessageToastTitle': 'Custom message sent',
  'Card.LiveBarrageSendCustomMessageToastDesc':
    'The receiver gets it via onCustomMessageReceived; it does NOT enter messageList',

  // AppendLocalTip card
  'Card.LiveBarrageAppendLocalTipDesc':
    'Locally construct a Barrage and push it straight into messageList.',
  'Card.LiveBarrageAppendLocalTipNoteSummary': 'appendLocalTip · local-only',
  'Card.LiveBarrageAppendLocalTipNote0Item0':
    'Local-only: not sent to the server, so the other side cannot see it. Use for pure client-side UX notices like "Welcome X" or "Host is about to go live", without consuming a real barrage slot.',
  'Card.LiveBarrageAppendLocalTipFieldTextPlaceholder': 'Local tip text to append',
  'Card.LiveBarrageAppendLocalTipToastTitle': 'Local tip appended',
  'Card.LiveBarrageAppendLocalTipToastDesc':
    'Only updates the local messageList; the other side will not receive it',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LiveBarrageSubscribeEventDesc':
    'This group subscribes to all [[BarrageEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onBarrageReceived]] events by default (demo handler; log rows prefixed with `[demo]<eventName>`). '
      + 'If a card below (unsubscribeEvent) canceled it, you can re-subscribe here by picking "all" or a single event; '
      + 'if the event is already subscribed, this call is an idempotent no-op.',
  'Card.LiveBarrageSubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-subscribe every event',
  'Card.LiveBarrageSubscribeEventToastTitle': 'Subscribed',
  'Card.LiveBarrageSubscribeEventToastDesc':
    'Next time the event fires, EventLog will also show a log row prefixed with "[demo]"',
  'Card.LiveBarrageUnsubscribeEventDesc':
    'Unsubscribe one or all events from [[BarrageEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onBarrageReceived]]. After unsubscribing, when the event fires again the "[demo] xxx" '
      + 'prefixed log row no longer appears (the unprefixed regular rows are still captured by the site\'s always-on log subscription). '
      + '⚠️ In real integrations the call MUST pass the EXACT SAME handler reference used for subscribeEvent, otherwise the SDK cannot find it and silently fails.',
  'Card.LiveBarrageUnsubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-unsubscribe every event',
  'Card.LiveBarrageUnsubscribeEventToastTitle': 'Unsubscribed',
  'Card.LiveBarrageUnsubscribeEventToastDesc':
    'Next time the event fires, EventLog will no longer show the "[demo]" prefixed log row',
  // Group intro — verified against BarrageState source
  'Card.LiveBarrageIntroSummary': 'Barrage has no on/off switch; whether you can send/receive depends only on being in a room',
  'Card.LiveBarrageIntro0Head': 'Key points',
  'Card.LiveBarrageIntro0Item0':
    'The source has NO barrage on/off switch (startBarrage/stopBarrage do not exist); whether you can send/receive depends only on being in a room — sending while not in a room is rejected by the underlying RoomEngine.',
  'Card.LiveBarrageIntro0Item1':
    'Two message types use different channels: text barrage auto-enters messageList and triggers onBarrageReceived; custom messages do NOT enter messageList — they are relayed only via onCustomMessageReceived, and the business layer must parse data itself.',
  'Card.LiveBarrageIntro0Item2':
    'Sending depends on the roomEngine instance existing (i.e. you are in a room); calling before entering silently fails / throws.',
  'Card.LiveBarrageIntro1Head': 'Common pitfalls',
  'Card.LiveBarrageIntro1Item0':
    'After sendCustomMessage, messageList length does not change — you must subscribe to onCustomMessageReceived to get it, otherwise it looks like "sent but nothing happened".',
  'Card.LiveBarrageIntro1Item1':
    'appendLocalTip is a pure local push into messageList — it is NOT sent to the server, so mistaking it for "another way to send" means the other side never receives it.',
  'Card.LiveBarrageIntro1Item2':
    'The custom message data is a raw string; the SDK does no schema validation, so the business side must agree on a schema and JSON.parse it.',
};
