// English (en-US) i18n resources — Gift & Likes state list.
//
// Key set MUST stay identical to `zh-CN/cards/liveGift.ts`; only the
// value differs. See `menuKey()` / `cardKey()` key derivation in the
// demo. zh-CN falls back to the Chinese literals, so only the English
// side needs explicit entries here.

export const liveGift: Record<string, string> = {
  'Card.LiveGiftSendGiftFieldGiftId': "Gift ID",
  'Card.LiveGiftSendGiftFieldCount': "Count",
  'Card.LiveGiftSendLikesFieldCount': "Count",
  'Card.LiveGiftSetLanguageFieldLanguage': "Language",
  'Card.LiveGiftSetLanguageFieldLanguageOptzh-Hans': "zh-Hans",
  'Card.LiveGiftSetLanguageFieldLanguageOpten': "en",
  'Menu.LiveGift': "Gift & Likes",
  'Menu.LiveGiftState': "Read gift state (giftInfoList / totalLikeCount)",
  'Menu.LiveGiftRefreshGiftList': "Refresh gift list",
  'Menu.LiveGiftSendGift': "Send gift",
  'Menu.LiveGiftSendLikes': "Send likes",
  'Menu.LiveGiftSetLanguage': "Set gift info display language",
  'Menu.LiveGiftGetGiftList': "Get gift list (deprecated, legacy compat only)",

  // GiftState card
  'Card.LiveGiftStateDesc':
    'Reactive snapshot of the gift-category list and cumulative like count.',

  // RefreshGiftList card
  'Card.LiveGiftRefreshGiftListDesc':
    "Pull the current live room's gift categories and list from the server.",
  'Card.LiveGiftRefreshGiftListNoteSummary': 'refreshGiftList',
  'Card.LiveGiftStateNoteSummary': 'live-gift.state · Auto-pull on open',
  'Card.LiveGiftStateNote0Item0':
    'Opening this card auto-calls refreshGiftList() to load the gift categories and catalog into reactive state giftInfoList — no need to click the refreshGiftList card. Data appears only after joining a room (currentLive.liveId present).',
  'Card.LiveGiftRefreshGiftListNote0Item0':
    'You MUST enter a room first: calling when currentLive.liveId is empty throws. Audience joinLive first, host startLive first.',
  'Card.LiveGiftRefreshGiftListNote0Item1':
    'Side effect: the result is written into the reactive giftInfoList; it also pre-loads the gift-effect animation assets (reduces the white screen on first gift send).',
  'Card.LiveGiftRefreshGiftListToastTitle': 'Gift list refreshed',
  'Card.LiveGiftRefreshGiftListToastDesc':
    'Pick a gift in the giftId dropdown of the sendGift card below',

  // SendGift card
  'Card.LiveGiftSendGiftDesc': 'Send the specified gift into the current live room.',
  'Card.LiveGiftSendGiftFieldGiftIdHelp':
    'Pick from the gift cards below; if empty, run refreshGiftList above first',
  'Card.LiveGiftSendGiftFieldGiftIdOpt':
    '(Please call refreshGiftList first to fetch the gift list)',
  'Card.LiveGiftSendGiftFieldGiftIdOptMeta': 'Click the refreshGiftList card above',
  'Card.LiveGiftSendGiftToastTitle': 'Gift sent',
  'Card.LiveGiftSendGiftToastDesc':
    'The receiver gets onReceiveGiftMessage and onGiftCountChanged',

  // SendLikes card
  'Card.LiveGiftSendLikesDesc': 'Send a like into the current live room.',
  'Card.LiveGiftSendLikesToastTitle': 'Like sent',
  'Card.LiveGiftSendLikesToastDesc':
    'The receiver gets onReceiveLikesMessage; totalLikeCount updates',

  // SetLanguage card
  'Card.LiveGiftSetLanguageDesc':
    'Set the display language for gift name / description and other info.',
  'Card.LiveGiftSetLanguageNoteSummary': 'setLanguage',
  'Card.LiveGiftSetLanguageNote0Item0':
    'After setting, you MUST re-call refreshGiftList to see the names / descriptions in the new language; switching the language alone does NOT re-fetch the cached gift list.',
  'Card.LiveGiftSetLanguageFieldLanguageOptzh-HansMeta': 'Simplified Chinese',
  'Card.LiveGiftSetLanguageFieldLanguageOptenMeta': 'English',
  'Card.LiveGiftSetLanguageToastTitle': 'Language switched',
  'Card.LiveGiftSetLanguageToastDesc':
    'Re-call refreshGiftList so gift names / descriptions use the new language',

  // GetGiftList card
  'Card.LiveGiftGetGiftListDesc':
    'Deprecated, equivalent to refreshGiftList but synchronously returns the gift-category array.',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LiveGiftSubscribeEventDesc':
    'This group subscribes to all [[LiveGiftEvents|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-ON_RECEIVE_GIFT_MESSAGE]] events by default (demo handler; log rows prefixed with `[demo]<eventName>`). '
      + 'If canceled by the unsubscribeEvent card below, you can re-subscribe here by picking "all" or a single event; '
      + 'if the event is already subscribed, this call is an idempotent no-op.',
  'Card.LiveGiftSubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-subscribe every event',
  'Card.LiveGiftSubscribeEventToastTitle': 'Subscribed',
  'Card.LiveGiftSubscribeEventToastDesc':
    'Next time the event fires, EventLog will also show a log row prefixed with "[demo]"',
  'Card.LiveGiftUnsubscribeEventDesc':
    'Unsubscribe one or all events from [[LiveGiftEvents|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-ON_RECEIVE_GIFT_MESSAGE]]. After unsubscribing, when the event fires again the "[demo] xxx" '
      + 'prefixed log row no longer appears (the unprefixed regular rows are still captured by the site\'s always-on log subscription). '
      + '⚠️ In real integrations the call MUST pass the EXACT SAME handler reference as subscribeEvent, otherwise the SDK cannot find it and silently fails.',
  'Card.LiveGiftUnsubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-unsubscribe every event',
  'Card.LiveGiftUnsubscribeEventToastTitle': 'Unsubscribed',
  'Card.LiveGiftUnsubscribeEventToastDesc':
    'Next time the event fires, EventLog will no longer show the "[demo]" prefixed log row',
  // Group intro — verified against LiveGiftState source
  'Card.LiveGiftIntroSummary': 'Every capability requires being in a room; the gift list is never auto-loaded',
  'Card.LiveGiftIntro0Head': 'Key points',
  'Card.LiveGiftIntro0Item0':
    'Sending gifts / likes / pulling the gift list all require currentLive.liveId to be non-empty (in a room) — calling while not in a room throws directly; the host must startLive and the audience must joinLive first.',
  'Card.LiveGiftIntro0Item1':
    'The gift list is never auto-loaded: giftInfoList starts empty, so you must actively refreshGiftList() (or the deprecated getGiftList()) to write it into the reactive data — pull the list before sendGift.',
  'Card.LiveGiftIntro0Item2':
    'The cumulative totalLikeCount is NOT incremented when you send a like; it is overwritten wholesale when you / others receive the server\'s like event — after you sendLikes the local number does not jump immediately.',
  'Card.LiveGiftIntro0Item3':
    'Gifts and likes are role-agnostic and unrelated to whether you are on-seat: host / audience / admin can all send; only "in a room" is checked.',
  'Card.LiveGiftIntro1Head': 'Common pitfalls',
  'Card.LiveGiftIntro1Item0':
    'To receive gift / like events you must subscribeEvent(LiveGiftEvents.<event>, cb) yourself; getGiftList is an async Promise (deprecated) — new code should use refreshGiftList.',
  'Card.LiveGiftIntro1Item1':
    'After setLanguage switches the language you must call refreshGiftList once more for the new language to show; switching language alone does not re-fetch the cached list.',
};
