// English (en-US) i18n resources — Playback Control state list.
//
// Key set MUST stay identical to `zh-CN/cards/livePlayer.ts`; only the value
// differs. See `menuKey()` / `cardKey()` key derivation in the demo.

export const livePlayer: Record<string, string> = {
  'Card.LivePlayerStateNote1Item0': "The player hides the underlying stream-source differences from the upper layer and uniformly exposes pause / resume / setVolume / switchResolution controls. Whether the underlying stream is real-time or CDN is chosen automatically by the engine based on the stream URL protocol; the integrator need not be aware of it.",
  'Card.LivePlayerSetVolumeFieldVolume': "Volume (0-100)",
  'Card.LivePlayerSetAutoHideDelayFieldDelay': "Delay (ms)",
  'Menu.LivePlayer': "Playback Control",
  'Menu.LivePlayerState': "Player render stage + read state",
  'Menu.LivePlayerPause': "Pause",
  'Menu.LivePlayerResume': "Resume",
  'Menu.LivePlayerRefresh': "Refresh (restore volume/resolution)",
  'Menu.LivePlayerSetVolume': "Set volume",
  'Menu.LivePlayerMute': "Mute",
  'Menu.LivePlayerUnmute': "Unmute",
  'Menu.LivePlayerRequestFullscreen': "Enter fullscreen",
  'Menu.LivePlayerExitFullscreen': "Exit fullscreen",
  'Menu.LivePlayerRequestPictureInPicture': "Enter picture-in-picture",
  'Menu.LivePlayerExitPictureInPicture': "Exit picture-in-picture",
  'Menu.LivePlayerSwitchResolution': "Switch resolution",
  'Menu.LivePlayerAddCustomButtons': "Inject custom buttons (experimental)",
  'Menu.LivePlayerShowControlBar': "Show control bar",
  'Menu.LivePlayerHideControlBar': "Hide control bar",
  'Menu.LivePlayerSetAutoHideDelay': "Set control bar auto-hide delay",

  // State card
  'Card.LivePlayerStateDesc':
    'Reactive snapshot of playback state (isPlaying / volume / resolution, ...).',
  'Card.LivePlayerStateNoteSummary': 'Playback-control prerequisites',
  'Card.LivePlayerStateNote0Item0':
    'LiveView is the observable prerequisite for ALL playback controls: pause / resume / setVolume / switchResolution only act on the currently mounted LiveView. A LiveView is mounted right below this card — if you see no picture, first confirm it is ready on this card.',

  // SwitchResolution card
  'Card.LivePlayerSwitchResolutionFieldIndex': 'Resolution',
  'Card.LivePlayerSwitchResolutionFieldIndexHelp':
    'You must start playback first; resolutionList fills only after that',
  'Card.LivePlayerSwitchResolutionFieldIndexOpt':
    '— waiting for resolutionList (start playback first)',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LivePlayerSubscribeEventDesc':
    'This group subscribes to all [[PlayerControlEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-PlayStateChange]] events by default (demo handler; log rows prefixed with `[demo]<eventName>`). '
      + 'If canceled by the unsubscribeEvent card below, you can re-subscribe here by picking "all" or a single event; '
      + 'if the event is already subscribed, this call is an idempotent no-op.',
  'Card.LivePlayerSubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-subscribe every event',
  'Card.LivePlayerSubscribeEventToastTitle': 'Subscribed',
  'Card.LivePlayerSubscribeEventToastDesc':
    'Next time the event fires, EventLog will also show a log row prefixed with "[demo]"',
  'Card.LivePlayerUnsubscribeEventDesc':
    'Unsubscribe one or all events from [[PlayerControlEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-PlayStateChange]]. After unsubscribing, when the event fires again the "[demo] xxx" '
      + 'prefixed log row no longer appears (the unprefixed regular rows are still captured by the site\'s always-on log subscription). '
      + '⚠️ In real integrations the call MUST pass the EXACT SAME handler reference used for subscribeEvent, otherwise the SDK cannot find it and silently fails.',
  'Card.LivePlayerUnsubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-unsubscribe every event',
  'Card.LivePlayerUnsubscribeEventToastTitle': 'Unsubscribed',
  'Card.LivePlayerUnsubscribeEventToastDesc':
    'Next time the event fires, EventLog will no longer show the "[demo]" prefixed log row',
  // Group intro — verified against LivePlayerState source
  'Card.LivePlayerIntroSummary': 'Playback auto-starts after entering a room; this group only exposes controls on top of a mounted player',
  'Card.LivePlayerIntro0Head': 'Key points',
  'Card.LivePlayerIntro0Item0':
    'You do NOT and cannot actively "start playback": after entering a live room (or going on-seat) playback starts automatically inside, and isPlaying becomes true as soon as liveId is obtained; this group only exposes pause / resume / refresh etc. on top of an already-mounted player — there is no startPlay/stopPlay.',
  'Card.LivePlayerIntro0Item1':
    'The pull-stream source difference (real-time / CDN) is invisible to the upper layer; the engine picks automatically by the pull URL protocol, and this group uniformly exposes only pause/resume/setVolume/switchResolution etc.',
  'Card.LivePlayerIntro0Item2':
    'The resolutionList starts empty and is only filled after playback starts; before that, switchResolution has no target to switch to.',
  'Card.LivePlayerIntro1Head': 'Common pitfalls',
  'Card.LivePlayerIntro1Item0':
    'Calling control APIs before entering a room / starting playback may fail and throw due to the engine instance or playback state; switchResolution has no target when resolutionList is empty.',
  'Card.LivePlayerIntro1Item1':
    'requestFullscreen() returns a FullscreenResult and does NOT throw: on failure success=false and isFullscreen is NOT set true, so the caller must check the return value — do not read only isFullscreen.',
  'Card.LivePlayerIntro1Item2':
    'switchResolution must receive the {label,value} object from resolutionList, not a bare number; setVolume only accepts 0–100 and throws if out of range.',
  'Card.LivePlayerIntro1Item3':
    'hideControlBar() "locks" the control bar hidden — hover / clicking the video will not bring it back; you must explicitly call showControlBar() to restore it.',
};
