// English (en-US) i18n resources — Login & User Profile state list.
//
// Key set MUST stay identical to `zh-CN/cards/login.ts`; only the value
// differs. Group title + example titles follow `Menu.<PascalCase>`; card
// descriptions / field labels / help / placeholders / notes / success-toast
// copy follow `Card.<PascalId><Suffix>` (see `cardKey()` in
// ExampleCard.vue). zh-CN falls back to the Chinese literals, so only
// the English side needs explicit entries here.

export const login: Record<string, string> = {
  'Card.LoginLoginFieldUserId': "User ID",
  'Card.LoginSetSelfInfoFieldUserName': "User name",
  'Card.LoginSetSelfInfoFieldAvatarUrl': "Avatar URL",
  'Menu.Login': "Login & User Profile",
  'Menu.LoginState': "Read login state (loginUserInfo / loginStatus)",
  'Menu.LoginLogin': "Login",
  'Menu.LoginLogout': "Logout",
  'Menu.LoginSetSelfInfo': "Edit user profile",

  // LoginState card description
  'Card.LoginStateDesc': 'Reactive snapshot of loginUserInfo (current user profile) / loginStatus (login state).',

  // Login card
  'Card.LoginLoginDesc':
    'Log in to IM via userId + userSig + sdkAppId. userSig is minted by the test service; production integrations must sign it on the business backend. After login, usually [[start live|startLive]]; see also [[official docs|officialDocsLogin]].',
  'Card.LoginLoginFieldUserIdHelp': 'IM user ID',
  'Card.LoginLoginFieldUserIdPlaceholder': 'Enter userId',

  // Logout card
  'Card.LoginLogoutDesc':
    'End the current IM session. After logout, loginUserInfo is cleared and loginStatus returns to UNKNOWN.',

  // SetSelfInfo card
  'Card.LoginSetSelfInfoDesc':
    'Update the current logged-in user\'s name and avatar. After the change, the SDK syncs it everywhere (live list, co-host candidates, ...).',
  'Card.LoginSetSelfInfoFieldUserNameHelp': 'New user name',
  'Card.LoginSetSelfInfoFieldUserNamePlaceholder': 'Leave empty to keep unchanged',
  'Card.LoginSetSelfInfoFieldAvatarUrlHelp': 'New avatar image URL',
  'Card.LoginSetSelfInfoFieldAvatarUrlPlaceholder': 'Leave empty to keep unchanged',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LoginSubscribeEventDesc':
    'This group subscribes to all [[LoginEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onLoginExpired]] events by default (demo handler; log rows prefixed with `[demo]<eventName>`). '
      + 'If canceled by the unsubscribeEvent card below, you can re-subscribe here by picking "all" or a single event; '
      + 'if the event is already subscribed, this call is an idempotent no-op.',
  'Card.LoginSubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-subscribe every event',
  'Card.LoginSubscribeEventToastTitle': 'Subscribed',
  'Card.LoginSubscribeEventToastDesc':
    'Next time the event fires, EventLog will also show a log row prefixed with "[demo]"',
  'Card.LoginUnsubscribeEventDesc':
    'Unsubscribe one or all events from [[LoginEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onLoginExpired]]. After unsubscribing, when the event fires again the "[demo] xxx" '
      + 'prefixed log row no longer appears (the unprefixed regular rows are still captured by the site\'s always-on log subscription). '
      + '⚠️ In real integrations the call MUST pass the EXACT SAME handler reference used for subscribeEvent, otherwise the SDK cannot find it and silently fails.',
  'Card.LoginUnsubscribeEventFieldEventHelp': 'Pick "(all events)" to bulk-unsubscribe every event',
  'Card.LoginUnsubscribeEventToastTitle': 'Unsubscribed',
  'Card.LoginUnsubscribeEventToastDesc':
    'Next time the event fires, EventLog will no longer show the "[demo]" prefixed log row',

  // Login group intro (G1): concrete hook inventory + login gate
  'Card.LoginIntroSummary': '{hook}() provides login state and the login / logout / edit-profile actions',
  'Card.LoginIntro0Head': 'Key points',
  'Card.LoginIntro0Item0':
    'The hook returns two reactive pieces of data: loginUserInfo (current user profile, null when not logged in) and loginStatus (enum: UNKNOWN / LOGINED); the actions are login / logout / setSelfInfo / subscribeEvent / unsubscribeEvent.',
  'Card.LoginIntro0Item1':
    'login is the single entry to the whole-site login state: after await login({ userId, userSig, sdkAppId }) succeeds, loginStatus.value === LOGINED, and every downstream capability waits on that signal. It is a side-effect API returning Promise<void> — the result lives in the ref; do NOT read the return value.',
  'Card.LoginIntro0Item2':
    'login throws on failure, and the module already logged which of userId / userSig / sdkAppId was missing — check those three first when debugging.',
  'Card.LoginIntro1Head': 'Prerequisite',
  'Card.LoginIntro1Item0':
    'login does NOT mint userSig for you: you must pass a userSig signed by your backend (this demo uses a test service). The demo may also inject an IM-proxy config that is auto-merged into the login params — that is demo-only behavior; in production the signing must be done on your backend.',
};
