export const BASEURL = {
  emoji: 'https://web.sdk.qcloud.com/im/assets/emoji-plugin/',
};
export const BASIC_EMOJI_URL_MAPPING: Record<string, string> = {
  '[TUIEmoji_Expect]': 'emoji_0@2x.png',
  '[TUIEmoji_Blink]': 'emoji_1@2x.png',
  '[TUIEmoji_Guffaw]': 'emoji_2@2x.png',
  '[TUIEmoji_KindSmile]': 'emoji_3@2x.png',
  '[TUIEmoji_Haha]': 'emoji_4@2x.png',
  '[TUIEmoji_Cheerful]': 'emoji_5@2x.png',
  '[TUIEmoji_Smile]': 'emoji_6@2x.png',
  '[TUIEmoji_Sorrow]': 'emoji_7@2x.png',
  '[TUIEmoji_Speechless]': 'emoji_8@2x.png',
  '[TUIEmoji_Amazed]': 'emoji_9@2x.png',
  '[TUIEmoji_Complacent]': 'emoji_10@2x.png',
  '[TUIEmoji_Lustful]': 'emoji_11@2x.png',
  '[TUIEmoji_Stareyes]': 'emoji_12@2x.png',
  '[TUIEmoji_Giggle]': 'emoji_13@2x.png',
  '[TUIEmoji_Daemon]': 'emoji_14@2x.png',
  '[TUIEmoji_Rage]': 'emoji_15@2x.png',
  '[TUIEmoji_Yawn]': 'emoji_16@2x.png',
  '[TUIEmoji_TearsLaugh]': 'emoji_17@2x.png',
  '[TUIEmoji_Silly]': 'emoji_18@2x.png',
  '[TUIEmoji_Wail]': 'emoji_19@2x.png',
  '[TUIEmoji_Kiss]': 'emoji_20@2x.png',
  '[TUIEmoji_Trapped]': 'emoji_21@2x.png',
  '[TUIEmoji_Fear]': 'emoji_22@2x.png',
  '[TUIEmoji_BareTeeth]': 'emoji_23@2x.png',
  '[TUIEmoji_FlareUp]': 'emoji_24@2x.png',
  '[TUIEmoji_Tact]': 'emoji_25@2x.png',
  '[TUIEmoji_Shit]': 'emoji_26@2x.png',
  '[TUIEmoji_ShutUp]': 'emoji_27@2x.png',
  '[TUIEmoji_Sigh]': 'emoji_28@2x.png',
  '[TUIEmoji_Hehe]': 'emoji_29@2x.png',
  '[TUIEmoji_Silent]': 'emoji_30@2x.png',
  '[TUIEmoji_Skull]': 'emoji_31@2x.png',
  '[TUIEmoji_Mask]': 'emoji_32@2x.png',
  '[TUIEmoji_Beer]': 'emoji_33@2x.png',
  '[TUIEmoji_Cake]': 'emoji_34@2x.png',
  '[TUIEmoji_RedPacket]': 'emoji_35@2x.png',
  '[TUIEmoji_Bombs]': 'emoji_36@2x.png',
  '[TUIEmoji_Ai]': 'emoji_37@2x.png',
  '[TUIEmoji_Celebrate]': 'emoji_38@2x.png',
  '[TUIEmoji_Bless]': 'emoji_39@2x.png',
  '[TUIEmoji_Flower]': 'emoji_40@2x.png',
  '[TUIEmoji_Watermelon]': 'emoji_41@2x.png',
  '[TUIEmoji_Cow]': 'emoji_42@2x.png',
  '[TUIEmoji_Fool]': 'emoji_43@2x.png',
  '[TUIEmoji_Surprised]': 'emoji_44@2x.png',
  '[TUIEmoji_Askance]': 'emoji_45@2x.png',
  '[TUIEmoji_Monster]': 'emoji_46@2x.png',
  '[TUIEmoji_Pig]': 'emoji_47@2x.png',
  '[TUIEmoji_Coffee]': 'emoji_48@2x.png',
  '[TUIEmoji_Ok]': 'emoji_49@2x.png',
  '[TUIEmoji_Heart]': 'emoji_50@2x.png',
  '[TUIEmoji_Sun]': 'emoji_51@2x.png',
  '[TUIEmoji_Moon]': 'emoji_52@2x.png',
  '[TUIEmoji_Star]': 'emoji_53@2x.png',
  '[TUIEmoji_Rich]': 'emoji_54@2x.png',
  '[TUIEmoji_Fortune]': 'emoji_55@2x.png',
  '[TUIEmoji_857]': 'emoji_56@2x.png',
  '[TUIEmoji_666]': 'emoji_57@2x.png',
  '[TUIEmoji_Prohibit]': 'emoji_58@2x.png',
  '[TUIEmoji_Convinced]': 'emoji_59@2x.png',
  '[TUIEmoji_Knife]': 'emoji_60@2x.png',
  '[TUIEmoji_Like]': 'emoji_61@2x.png',
};

export const BASIC_EMOJI_NAME_MAPPING: Record<string, string> = {
  '[TUIEmoji_Smile]': '[Smile]',
  '[TUIEmoji_Expect]': '[Expect]',
  '[TUIEmoji_Blink]': '[Blink]',
  '[TUIEmoji_Guffaw]': '[Laugh]',
  '[TUIEmoji_KindSmile]': '[Kind Smile]',
  '[TUIEmoji_Haha]': '[Haha]',
  '[TUIEmoji_Cheerful]': '[Cheerful]',
  '[TUIEmoji_Speechless]': '[Speechless]',
  '[TUIEmoji_Amazed]': '[Amazed]',
  '[TUIEmoji_Sorrow]': '[Sorrow]',
  '[TUIEmoji_Complacent]': '[Complacent]',
  '[TUIEmoji_Silly]': '[Silly]',
  '[TUIEmoji_Lustful]': '[Lustful]',
  '[TUIEmoji_Giggle]': '[Giggle]',
  '[TUIEmoji_Kiss]': '[Kiss]',
  '[TUIEmoji_Wail]': '[Wail]',
  '[TUIEmoji_TearsLaugh]': '[Tears of Laughter]',
  '[TUIEmoji_Trapped]': '[Trapped]',
  '[TUIEmoji_Mask]': '[Mask]',
  '[TUIEmoji_Fear]': '[Fear]',
  '[TUIEmoji_BareTeeth]': '[Bare Teeth]',
  '[TUIEmoji_FlareUp]': '[Flare Up]',
  '[TUIEmoji_Yawn]': '[Yawn]',
  '[TUIEmoji_Tact]': '[Tact]',
  '[TUIEmoji_Stareyes]': '[Star Eyes]',
  '[TUIEmoji_ShutUp]': '[Shut Up]',
  '[TUIEmoji_Sigh]': '[Sigh]',
  '[TUIEmoji_Hehe]': '[Hehe]',
  '[TUIEmoji_Silent]': '[Silent]',
  '[TUIEmoji_Surprised]': '[Surprised]',
  '[TUIEmoji_Askance]': '[Askance]',
  '[TUIEmoji_Ok]': '[OK]',
  '[TUIEmoji_Shit]': '[Poop]',
  '[TUIEmoji_Monster]': '[Monster]',
  '[TUIEmoji_Daemon]': '[Daemon]',
  '[TUIEmoji_Rage]': '[Rage]',
  '[TUIEmoji_Fool]': '[Fool]',
  '[TUIEmoji_Pig]': '[Pig]',
  '[TUIEmoji_Cow]': '[Cow]',
  '[TUIEmoji_Ai]': '[AI]',
  '[TUIEmoji_Skull]': '[Skull]',
  '[TUIEmoji_Bombs]': '[Bombs]',
  '[TUIEmoji_Coffee]': '[Coffee]',
  '[TUIEmoji_Cake]': '[Cake]',
  '[TUIEmoji_Beer]': '[Beer]',
  '[TUIEmoji_Flower]': '[Flower]',
  '[TUIEmoji_Watermelon]': '[Watermelon]',
  '[TUIEmoji_Rich]': '[Rich]',
  '[TUIEmoji_Heart]': '[Heart]',
  '[TUIEmoji_Moon]': '[Moon]',
  '[TUIEmoji_Sun]': '[Sun]',
  '[TUIEmoji_Star]': '[Star]',
  '[TUIEmoji_RedPacket]': '[Red Packet]',
  '[TUIEmoji_Celebrate]': '[Celebrate]',
  '[TUIEmoji_Bless]': '[Bless]',
  '[TUIEmoji_Fortune]': '[Fortune]',
  '[TUIEmoji_Convinced]': '[Convinced]',
  '[TUIEmoji_Prohibit]': '[Prohibit]',
  '[TUIEmoji_666]': '[666]',
  '[TUIEmoji_857]': '[857]',
  '[TUIEmoji_Knife]': '[Knife]',
  '[TUIEmoji_Like]': '[Like]',
};
