// 简体中文 (zh-CN) i18n 资源 — 与 `en-US/cards/battle.ts` 键集合保持一致；仅值不同。

export const battle: Record<string, string> = {
  'Card.BattleRequestBattleFieldUserId': "target userId",
  'Card.BattleRequestBattleFieldDuration': "config.duration (seconds)",
  'Card.BattleRequestBattleFieldNeedResponse': "config.needResponse",
  'Card.BattleRequestBattleFieldExtensionInfo': "config.extensionInfo",
  'Card.BattleRequestBattleFieldTimeout': "timeout (seconds)",
  'Card.BattleCancelBattleRequestFieldBattleId': "battleId",
  'Card.BattleCancelBattleRequestFieldUserId': "target userId",
  'Card.BattleAcceptBattleFieldBattleId': "battleId",
  'Card.BattleRejectBattleFieldBattleId': "battleId",
  'Card.BattleExitBattleFieldBattleId': "battleId",
  'Menu.Battle': "PK 对战",
  'Menu.BattleState': "读取 PK 状态（currentBattleInfo / battleUsers / battleScore）",
  'Menu.BattleRequestBattle': "发起 PK 邀请（仅主播）",
  'Menu.BattleCancelBattleRequest': "取消已发出的 PK 邀请（仅主播）",
  'Menu.BattleAcceptBattle': "接受 PK 邀请（仅主播）",
  'Menu.BattleRejectBattle': "拒绝 PK 邀请（仅主播）",
  'Menu.BattleExitBattle': "退出 PK（仅主播）",

  // BattleState card
  'Card.BattleStateDesc':
    '三个只读响应式：currentBattleInfo / battleUsers / battleScore 的状态快照。',
  'Card.BattleStateNoteSummary': 'battle 状态读取',
  'Card.BattleStateNote0Item0':
    'battleScore（分数）不通过事件订阅获取：SDK 在内部通过 onBattleScoreChanged 更新响应式 Map。业务侧只需 watch(battleScore) —— 不要订阅 onBattleScoreChanged（它不在 BattleEvent 枚举中）。',

  // RequestBattle card
  'Card.BattleRequestBattleDesc':
    '向已跨房连线的对端主播发起 PK 邀请。',
  'Card.BattleRequestBattleNoteSummary': 'requestBattle · 前置与语义',
  'Card.BattleRequestBattleNote0Item0':
    '必须先建立 co-host 组的跨房连线：Battle 依赖 CoHost 链接。没有链接时目标下拉为空，直接调用会被 SDK 立即判定为「已断开」并执行 resetBattleState。',
  'Card.BattleRequestBattleNote0Item1':
    'needResponse 决定应答流程：true 表示需要对方 acceptBattle / rejectBattle 才生效；false 则跳过双向应答，直接开始 PK。',
  'Card.BattleRequestBattleFieldUserIdHelp': '从 co-host 组里连线成功的对端主播中选择',
  'Card.BattleRequestBattleFieldDurationHelp': 'PK 倒计时秒数（到期自动结束）',
  'Card.BattleRequestBattleFieldNeedResponseHelp': 'true = 需要对方应答',
  'Card.BattleRequestBattleFieldExtensionInfoPlaceholder': '可选，透传给对端的业务字符串',
  'Card.BattleRequestBattleFieldUserIdOpt': '（请先在 co-host 组建立跨房连线）',
  'Card.BattleRequestBattleFieldUserIdOptMeta': '先运行 co-host.requestHostConnection + 对端 acceptHostConnection',
  'Card.BattleRequestBattleToastTitle': 'PK 邀请已发出',
  'Card.BattleRequestBattleToastDesc':
    'needResponse=true 时对端触发 onBattleRequestReceived；应答后本端触发 onBattleRequestAccept / Reject / Timeout',

  // CancelBattleRequest card
  'Card.BattleCancelBattleRequestDesc': '在对端应答前取消已发出的 PK 邀请。',
  'Card.BattleCancelBattleRequestNoteSummary': 'cancelBattleRequest · 参数契约',
  'Card.BattleCancelBattleRequestNote0Item0':
    'userIdList 必须与传给 requestBattle 的完全一致：取消是点对点操作，不匹配的 userId 会被 SDK 静默忽略。',
  'Card.BattleCancelBattleRequestFieldBattleIdPlaceholder': '待取消的 battleId',
  'Card.BattleCancelBattleRequestFieldBattleIdHelp': '自动填入；可手动覆盖',
  'Card.BattleCancelBattleRequestFieldUserIdPlaceholder': '被邀请的对端主播 userId',
  'Card.BattleCancelBattleRequestToastTitle': 'PK 邀请已取消',
  'Card.BattleCancelBattleRequestToastDesc': '对端触发 onBattleRequestCancelled',

  // AcceptBattle card
  'Card.BattleAcceptBattleDesc': '接受收到的 PK 邀请。',
  'Card.BattleAcceptBattleFieldBattleIdPlaceholder': '收到邀请后自动填充',
  'Card.BattleAcceptBattleToastTitle': '已接受 PK',
  'Card.BattleAcceptBattleToastDesc':
    'SDK 触发 onBattleStarted；battleScore 开始接收变更',

  // RejectBattle card
  'Card.BattleRejectBattleDesc': '拒绝当前收到的 onBattleRequestReceived。对端触发 onBattleRequestReject。',
  'Card.BattleRejectBattleFieldBattleIdPlaceholder': '收到邀请后自动填充',
  'Card.BattleRejectBattleToastTitle': '已拒绝 PK',
  'Card.BattleRejectBattleToastDesc': '对端触发 onBattleRequestReject',

  // ExitBattle card
  'Card.BattleExitBattleDesc': '主动退出当前 PK。',
  'Card.BattleExitBattleNoteSummary': 'exitBattle · 退出与结束语义',
  'Card.BattleExitBattleNote0Item0':
    '单方退出：调用方不再计入分数；其他主播的 PK 继续进行，分数持续更新。不会触发 onBattleEnded。',
  'Card.BattleExitBattleNote0Item1':
    '全员退出：仅当所有参与主播都调用 exitBattle 时，SDK 才判定 PK 结束，并以 reason = allMemberExit 触发 onBattleEnded。',
  'Card.BattleExitBattleNote0Item2':
    '倒计时到期：若无人主动退出且倒计时归零，SDK 自动结束 PK，并以 reason = timeOver 触发 onBattleEnded。',
  'Card.BattleExitBattleFieldBattleIdPlaceholder': '当前 PK 的 battleId',
  'Card.BattleExitBattleFieldBattleIdHelp': '自动填入；可手动覆盖',
  'Card.BattleExitBattleToastTitle': '已退出 PK',
  'Card.BattleExitBattleToastDesc':
    '本端 battleUsers 更新；SDK 视全员退出情况触发 onBattleEnded',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.BattleSubscribeEventDesc': "本组挂载时已默认订阅 [[BattleEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onBattleStarted]] 全部事件（演示 handler；带 `[demo]<事件名>` 前缀的日志行）。若被下方 unsubscribeEvent 卡片取消，可在此选择\"全部\"或单个事件重新订阅；若该事件已在订阅中，本次调用是幂等空操作。",
  'Card.BattleSubscribeEventFieldEventHelp': "选 (all events) 表示对全部事件批量订阅",
  'Card.BattleSubscribeEventToastTitle': "已订阅",
  'Card.BattleSubscribeEventToastDesc': "该事件下次触发时，EventLog 会同时出现 \"[demo]\" 前缀的日志行",
  'Card.BattleUnsubscribeEventDesc': "从 [[BattleEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onBattleStarted]] 中取消订阅一个或全部事件。取消后该事件再次触发时，EventLog 里 \"[demo] xxx\" 前缀的日志行不再出现（不带前缀的常规事件行仍由站点的常驻日志订阅捕获）。⚠️ 真实业务中调用必须传与 subscribeEvent 时「完全相同」的 handler 引用，否则 SDK 会查找不到并静默失败。",
  'Card.BattleUnsubscribeEventFieldEventHelp': "选 (all events) 表示对全部事件批量取消订阅",
  'Card.BattleUnsubscribeEventToastTitle': "已取消订阅",
  'Card.BattleUnsubscribeEventToastDesc': "该事件下次触发时，EventLog 不再出现 \"[demo]\" 前缀的日志行",
  // Group intro — verified against BattleState source
  'Card.BattleIntroSummary': 'PK 建在跨房连线之上，由 SDK 比对分、自动计时',
  'Card.BattleIntro0Head': '关键点',
  'Card.BattleIntro0Item0':
    'PK 只负责「比分 / 倒计时 / 起止」，不建立也不校验跨房连线——目标 userId 来自已连线的对端主播，务必先在 useCoHostState 里 requestHostConnection 建立连线，再 requestBattle。',
  'Card.BattleIntro0Item1':
    '切换 / 离开直播间会自动清空 PK 状态：currentBattleInfo 置空、battleUsers 清空、battleScore 置空，避免上一个房间的 battleId 泄漏到新房间（这是模块级行为，业务侧不要自己 watch 房间来 reset）。',
  'Card.BattleIntro0Item2':
    '本组不暴露 reset 接口，PK 状态由「房间切换」和「PK 结束 / 退出」两个场景内部自动收尾，业务侧无需手动维护。',
  'Card.BattleIntro1Head': '常见陷阱',
  'Card.BattleIntro1Item0':
    '比分不是你写入的：SDK 的 onBattleScoreChanged 直接改写 battleScore 这个 ref，它不在 BattleEvent 枚举里，subscribeEvent 收不到比分，应 watch(battleScore)。',
  'Card.BattleIntro1Item1':
    '剩余秒数不是独立 ref：demo 里用 currentBattleInfo.endTime − 现在 现算，endTime 才是真实结束时间戳。',
  'Card.BattleIntro1Item2':
    '单方退出不算 PK 结束：只有全部参战主播退出或倒计时归零才触发 onBattleEnded；本端退出后其他人 PK 继续、比分照常更新。',
};
