// 简体中文 (zh-CN) i18n 资源 — 与 `en-US/cards/login.ts` 键集合保持一致；仅值不同。

export const login: Record<string, string> = {
  'Card.LoginLoginFieldUserId': "userId",
  'Card.LoginSetSelfInfoFieldUserName': "userName",
  'Card.LoginSetSelfInfoFieldAvatarUrl': "avatarUrl",
  'Menu.Login': "登录与用户资料",
  'Menu.LoginState': "读取登录状态（loginUserInfo / loginStatus）",
  'Menu.LoginLogin': "登录",
  'Menu.LoginLogout': "退出登录",
  'Menu.LoginSetSelfInfo': "修改用户资料",
  'Card.LoginStateDesc':
    'loginUserInfo（当前用户资料）/ loginStatus（登录状态）的响应式快照。',
  'Card.LoginLoginDesc':
    '通过 userId + userSig + sdkAppId 登录 IM。userSig 由测试服务签发；生产接入必须在业务后端完成签名。登录后通常接着 [[开始直播|startLive]]，详见 [[官方文档|officialDocsLogin]]。',
  'Card.LoginLoginFieldUserIdHelp': 'IM 用户 ID',
  'Card.LoginLoginFieldUserIdPlaceholder': '请输入 userId',
  'Card.LoginLogoutDesc':
    '结束当前 IM 会话。登出后 loginUserInfo 被清空，loginStatus 回到 UNKNOWN。',
  'Card.LoginSetSelfInfoDesc':
    '更新当前登录用户的昵称与头像。变更后 SDK 会在各处同步（直播列表、跨房候选等）。',
  'Card.LoginSetSelfInfoFieldUserNameHelp': '新的用户昵称',
  'Card.LoginSetSelfInfoFieldUserNamePlaceholder': '留空表示保持不变',
  'Card.LoginSetSelfInfoFieldAvatarUrlHelp': '新的头像图片 URL',
  'Card.LoginSetSelfInfoFieldAvatarUrlPlaceholder': '留空表示保持不变',

  // subscribeEvent / unsubscribeEvent (shared, generated by buildSubscriptionCards)
  'Card.LoginSubscribeEventDesc': "本组挂载时已默认订阅 [[LoginEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onLoginExpired]] 全部事件（演示 handler；带 `[demo]<事件名>` 前缀的日志行）。若被下方 unsubscribeEvent 卡片取消，可在此选择\"全部\"或单个事件重新订阅；若该事件已在订阅中，本次调用是幂等空操作。",
  'Card.LoginSubscribeEventFieldEventHelp': '选 (all events) 表示对全部事件批量订阅',
  'Card.LoginSubscribeEventToastTitle': "已订阅",
  'Card.LoginSubscribeEventToastDesc': "该事件下次触发时，EventLog 会同时出现 \"[demo]\" 前缀的日志行",
  'Card.LoginUnsubscribeEventDesc': "从 [[LoginEvent|https://web.sdk.qcloud.com/trtc/live/web/doc/zh/index.html#event-onLoginExpired]] 中取消订阅一个或全部事件。取消后该事件再次触发时，EventLog 里 \"[demo] xxx\" 前缀的日志行不再出现（不带前缀的常规事件行仍由站点的常驻日志订阅捕获）。⚠️ 真实业务中调用必须传与 subscribeEvent 时「完全相同」的 handler 引用，否则 SDK 会查找不到并静默失败。",
  'Card.LoginUnsubscribeEventFieldEventHelp': '选 (all events) 表示对全部事件批量取消订阅',
  'Card.LoginUnsubscribeEventToastTitle': "已取消订阅",
  'Card.LoginUnsubscribeEventToastDesc': "该事件下次触发时，EventLog 不再出现 \"[demo]\" 前缀的日志行",

  // Login group intro (G1): concrete hook inventory + login gate
  'Card.LoginIntroSummary': '{hook}() 提供登录态与登录 / 登出 / 改资料动作',
  'Card.LoginIntro0Head': '关键点',
  'Card.LoginIntro0Item0':
    '钩子返回两个响应式数据：loginUserInfo（当前用户资料，未登录为 null）与 loginStatus（枚举：UNKNOWN / LOGINED）；动作有 login / logout / setSelfInfo / subscribeEvent / unsubscribeEvent。',
  'Card.LoginIntro0Item1':
    'login 是整站登录态的唯一入口：await login({ userId, userSig, sdkAppId }) 成功后 loginStatus.value === LOGINED，下游所有能力都等这个信号。它是副作用接口，返回 Promise<void>——结果写在 ref 里，不要读返回值。',
  'Card.LoginIntro0Item2':
    'login 失败会直接抛错，且模块已在日志中标明缺了 userId / userSig / sdkAppId 中的哪一个，排错先看这三项。',
  'Card.LoginIntro1Head': '业务前提',
  'Card.LoginIntro1Item0':
    'login 不会替你签发 userSig：必须传入由你后端签发的 userSig（本 demo 用测试服务生成）。demo 还可能注入一份 IM 代理配置并自动合并进登录参数，那是 demo 专属行为，生产请由后端完成签名。',
};
