/**
 * Aegis Data Reporting Service - Stub Version
 *
 * This is a stub implementation for the GitHub demo version.
 * All reporting functions are no-ops.
 *
 * Auto-generated by publish-github.js
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AegisStub = any;

export function initAegis(_uin?: string): AegisStub { return null as any; }

export function getAegis(): AegisStub | null { return null; }

export function setAegisUin(_uin: string): void {}

export function reportEvent(_eventName: string, ..._ext1Parts: (string | undefined)[]): void {}

export function destroyAegis(): void {}

export function createSceneDurationTracker(_page: string, _scene: string, _subScene?: string): {
  cleanup: () => void;
} { return { cleanup: () => {} }; }

export function reportSceneSelect(_page: string, _scene: string, _subScene?: string): void {}

export function reportIndustrySwitcherClick(_subScene: string): void {}

export function reportLinkClick(..._parts: (string | undefined)[]): void {}

export function reportQrcodeView(_page: string, _scene?: string, _platform?: string): void {}

export function reportMedicalPickerClick(_pickerType: string): void {}

export function reportMedicalShowroomClick(): void {}

export default {
  initAegis,
  getAegis,
  setAegisUin,
  reportEvent,
  reportSceneSelect,
  reportIndustrySwitcherClick,
  reportLinkClick,
  reportQrcodeView,
  reportMedicalPickerClick,
  reportMedicalShowroomClick,
  createSceneDurationTracker,
  destroyAegis,
};
