import Avatar from './Avatar.vue';
import {
  DEFAULT_USER_AVATAR,
  DEFAULT_GROUP_AVATAR_WORK,
  DEFAULT_GROUP_AVATAR_PUBLIC,
  DEFAULT_GROUP_AVATAR_MEETING,
  DEFAULT_GROUP_AVATAR_AVCHATROOM,
  DEFAULT_GROUP_AVATAR_COMMON,
} from './constants/avatar';

export {
  Avatar,
  DEFAULT_USER_AVATAR,
  DEFAULT_GROUP_AVATAR_WORK,
  DEFAULT_GROUP_AVATAR_PUBLIC,
  DEFAULT_GROUP_AVATAR_MEETING,
  DEFAULT_GROUP_AVATAR_AVCHATROOM,
  DEFAULT_GROUP_AVATAR_COMMON,
};
export type { AvatarSize, AvatarShape, AvatarProps } from './Avatar.vue';
